import { createHash } from "node:crypto";

export interface ArtifactManifest { schemaVersion: 1; artifactId: string; source: string; branch: string; commitSha: string; parentShas: string[]; createdAt: string; sizeBytes: number; sha256?: string; fileCount?: number; }
export interface ArtifactVerification { valid: boolean; errors: string[]; warnings: string[]; }
const SHA40=/^[0-9a-f]{40}$/i; const SHA64=/^[0-9a-f]{64}$/i;
export function verifyManifest(m: ArtifactManifest): ArtifactVerification { const errors:string[]=[]; const warnings:string[]=[]; if(m.schemaVersion!==1) errors.push("unsupported schemaVersion"); if(!m.artifactId.trim()) errors.push("artifactId is required"); if(!m.source.trim()) errors.push("source is required"); if(!m.branch.trim()) errors.push("branch is required"); if(!SHA40.test(m.commitSha)) errors.push("commitSha must be a 40-character hex SHA"); if(!m.parentShas.every(s=>SHA40.test(s))) errors.push("every parent SHA must be a 40-character hex SHA"); if(!Number.isSafeInteger(m.sizeBytes)||m.sizeBytes<0) errors.push("sizeBytes must be a non-negative safe integer"); if(m.sha256!==undefined&&!SHA64.test(m.sha256)) errors.push("sha256 must be a 64-character hex digest"); if(m.fileCount!==undefined&&(!Number.isSafeInteger(m.fileCount)||m.fileCount<0)) errors.push("fileCount must be a non-negative safe integer"); if(m.parentShas.length===0) warnings.push("no parent commits recorded; provenance chain cannot be independently reconstructed"); return {valid:errors.length===0,errors,warnings}; }
export function verifyArtifactBytes(bytes:Uint8Array, expectedSha256:string, expectedSizeBytes:number):ArtifactVerification { const errors:string[]=[]; const warnings:string[]=[]; if(bytes.byteLength!==expectedSizeBytes) errors.push("size mismatch: expected "+expectedSizeBytes+", got "+bytes.byteLength); if(!SHA64.test(expectedSha256)){errors.push("expectedSha256 must be a 64-character hex digest"); return {valid:false,errors,warnings};} const actual=createHash("sha256").update(bytes).digest("hex"); if(actual!==expectedSha256.toLowerCase()) errors.push("sha256 mismatch: expected "+expectedSha256+", got "+actual); return {valid:errors.length===0,errors,warnings}; }
export interface ImportPlan { artifactId:string; source:string; targetRepository:string; targetBranch:string; commitSha:string; action:"CREATE_BRANCH"|"UPDATE_BRANCH"|"NOOP"; forcePush:false; verificationRequired:true; }
export function planImport(m:ArtifactManifest,targetRepository:string,existingRemoteSha?:string):ImportPlan { if(!verifyManifest(m).valid) throw new Error("cannot create import plan from an invalid manifest"); const action=existingRemoteSha===m.commitSha?"NOOP":existingRemoteSha?"UPDATE_BRANCH":"CREATE_BRANCH"; return {artifactId:m.artifactId,source:m.source,targetRepository,targetBranch:m.branch,commitSha:m.commitSha,action,forcePush:false,verificationRequired:true}; }
